### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'

### ISSUE THREAD

**Issue by andreabotti** [architecture-building-systems/esoreader#3] opened 2017-03-18 18:13 UTC
Hello,
I am trying to run esoreader, typing in the snippet:
```
path_to_eso = r'../CP_P1203/output/EP_CP1203_000000130/eplusout.eso'
print(path_to_eso)
eso = esoreader.read_from_path(path_to_eso)

```
And receive this error - which I am not sure how to address. Full traceback:
```
Traceback (most recent call last):
  File "D:\Dropbox\EDU_EngD\ROAST\2_ENGINE\_SIMS\_postproc_python_code\PY01_jeplus_output_esoreader_v1.py", line 42, in <module>
    eso = esoreader.read_from_path(path_to_eso)
  File "C:\Program Files\Anaconda3\lib\site-packages\esoreader.py", line 71, in read_from_path
    eso = EsoFile(eso_file)
  File "C:\Program Files\Anaconda3\lib\site-packages\esoreader.py", line 108, in __init__
    self.dd = self._read_data_dictionary()
  File "C:\Program Files\Anaconda3\lib\site-packages\esoreader.py", line 168, in _read_data_dictionary
    in self.eso_file.next().split(',')[-2:]]
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'
```

**Comment by daren-thomas** [comment] 2017-08-23 14:10
I'll have to port this to Python3 someday... unless you want to post a pull request that is compatible with both?

**Comment by andreabotti** [comment] 2018-01-23 08:41
Hi @daren-thomas , did you manage to fix this? I have encountered the same error when writing a script that reads hourly results.
From your answer, should I take it that this error would not arise using Python 2?

**Comment by daren-thomas** [comment] 2018-01-23 09:07
Hi @andreabotti yes, I haven't ported this at all and it works in Python2...

Could you attach a sample .eso file for me to test on?

**Comment by andreabotti** [comment] 2018-01-23 10:45
@daren-thomas while using python 3.5.2, the errors appear randomly, usually more likely for bigger parametric jobs (I included the `esoreader` functions to collect simulation results produced with the tool [jeplus](http://www.jeplus.org/wiki/doku.php)).

My error is:
```
Traceback (most recent call last):
  File "C:\ROASST_2\2_JEPLUS_JESS\P1202\P1202_MF_GTWDSY1\in_parameters\PP_read_from_eso.py", line 190, in <module>
    dd,data = esoreader.read(ESO_filepath)            
  File "C:\ROASST_2\2_JEPLUS_JESS\P1202\P1202_MF_GTWDSY1\in_parameters\esoreader.py", line 61, in read
    eso = read_from_path(eso_file_path)
  File "C:\ROASST_2\2_JEPLUS_JESS\P1202\P1202_MF_GTWDSY1\in_parameters\esoreader.py", line 71, in read_from_path
    eso = EsoFile(eso_file)
  File "C:\ROASST_2\2_JEPLUS_JESS\P1202\P1202_MF_GTWDSY1\in_parameters\esoreader.py", line 108, in __init__
    self.dd = self._read_data_dictionary()
  File "C:\ROASST_2\2_JEPLUS_JESS\P1202\P1202_MF_GTWDSY1\in_parameters\esoreader.py", line 186, in _read_data_dictionary
    line = self.eso_file.__next__().strip()
StopIteration
```

**Comment by daren-thomas** [comment] 2018-01-23 15:19
I've just installed a Python 3.5.2 environment and run it through a random .eso file I still had lying around - without any hickups. I can't reproduce this. Do you have an `.eso` file that reproduces the error? If you attach it here I can try it with that one. Or we can open a private channel for exchanging it if you don't want the file public...

**Comment by daren-thomas** [comment] 2018-01-23 15:31
oh wait... @andreabotti did you install from pypi or are you using the code on github? I found an error in `setup.py` that resulted in the wrong `.tar.gz` being downloaded from github: I fixed that and `pip install --upgrade esoreader` should fix your problem.

**Comment by andreabotti** [comment] 2018-01-24 10:52
@daren-thomas I have installed it using `pip install esoreader` and upgraded with `pip install esoreader --upgrade`.
esoreader generally works fine, and the errors appear randomly, while all eso files are generated in the same manner (hence there is no reason why one should be shaped/structured differently than another

**Comment by daren-thomas** [comment] 2018-01-24 12:05
@andreabotti when you say randomly - do you mean:

1. the same `.eso` file sometimes works and sometimes doesn't *or*
2. some `.eso` files work and some don't

Because, if option 1, then please just send me a sample `.eso` file that doesn't work so I can debug this issue for you.

**Comment by andreabotti** [comment] 2018-01-24 19:46
@daren-thomas it's 2.
However I have now upgraded `esoreader` (I thought it was up-to-date but it was not) and I have not incurred in the error since. I will let you know if/when I get more errors. Thanks a lot for now

**Comment by daren-thomas** [comment] 2018-01-29 14:02
@andreabotti ok, thank you for helping me debug this. I'm closing the issue now.

**Closed by daren-thomas** 2018-01-29 14:02 UTC
